# --- 1. 后端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
      - name: java-backend
        # 记得换成你自己的后端镜像地址
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
spec:
  type: NodePort
  selector:
    app: java-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

---
# --- 2. 前端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      containers:
      - name: vue-frontend
        # 记得换成你自己的前端镜像地址
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/vue-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
spec:
  type: NodePort
  selector:
    app: vue-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001