# --- 1. 后端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2
  template:
    spec:
      # 【新增】在这里出示刚才创建的通行证
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: java-backend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-backend:latest
        ports:
        - containerPort: 8080
---
# --- 2. 前端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 2
  template:
    spec:
      # 【新增】这里也需要，因为它们都在私有仓库
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: vue-frontend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/vue-frontend:latest
        ports:
        - containerPort: 80