# --- 1. 后端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-backend  # 这里的标签
  template:
    metadata:
      labels:
        app: java-backend  # 必须和这里完全一致
    spec:
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: java-backend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-app-auto:backend-latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-service
spec:
  type: NodePort
  selector:
    app: java-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

---
# --- 2. 前端部署 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-frontend
  template:
    metadata:
      labels:
        app: vue-frontend
    spec:
      imagePullSecrets:
      - name: aliyun-acr-secret
      containers:
      - name: vue-frontend
        image: crpi-isruoknymwjt6jux.cn-hangzhou.personal.cr.aliyuncs.com/dja-repo/java-app-auto:frontend-latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
spec:
  type: NodePort
  selector:
    app: vue-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001